import { Platform } from 'react-native';

const buildImageSource = (iosSrc: string, androidSrc: string): { uri: string } => {
    return { uri: Platform.OS === 'ios' ? iosSrc : androidSrc };
};

export const Images = {
    // Backgrounds
    backgroundPattern: buildImageSource('BackgroundPattern', 'background_pattern'),
    BackgroundShapes: buildImageSource('BackgroundShapes', 'background_shapes'),
    // Visuals
    ImageFirstAccount: buildImageSource('ImageFirstAccount', 'image_first_account'),
    ImageNoEvents: buildImageSource('ImageNoEvents', 'image_no_events'),
    ImageProfile: buildImageSource('ImageProfile', 'image_profile'),
    ImageNoContacts: buildImageSource('ImageNoContacts', 'image_no_contacts'),
    ImageAddAccount: buildImageSource('ImageAddAccount', 'image_add_account'),
    ImageNewAccount: buildImageSource('ImageNewAccount', 'image_new_account'),
    ImageSecretWarning: buildImageSource('ImageSecretWarning', 'image_secret_warning'),
    ImageManageAccounts: buildImageSource('ImageManageAccounts', 'image_manage_accounts'),
    ImageSecurityFirst: buildImageSource('ImageSecurityFirst', 'image_security_first'),
    ImageSendReceive: buildImageSource('ImageSendReceive', 'image_send_receive'),
    ImagePincode: buildImageSource('ImagePincode', 'image_pincode'),
    ImageBiometric: buildImageSource('ImageBiometric', 'image_biometric'),
    ImageNotifications: buildImageSource('ImageNotifications', 'image_notifications'),
    ImageComplete: buildImageSource('ImageComplete', 'image_complete'),
    ImageCloudAlert: buildImageSource('ImageCloudAlert', 'image_cloud_alert'),
    ImageWarningShield: buildImageSource('ImageWarningShield', 'image_warning_shield'),
    ImageCoinWallet: buildImageSource('ImageCoinWallet', 'image_coin_wallet'),
    // Xumm
    xummLogo: buildImageSource('XummLogo', 'xumm_logo'),
    xummIcon: buildImageSource('XummIcon', 'xumm_icon'),
    SideGradient: buildImageSource('SideGradient', 'side_gradient'),
    // Icons
    IconTabBarScan: buildImageSource('IconTabBarScan', 'icon_tabbar_scan'),
    IconTabBarHome: buildImageSource('IconTabBarHome', 'icon_tabbar_home'),
    IconTabBarHomeSelected: buildImageSource('IconTabBarHomeSelected', 'icon_tabbar_home_selected'),
    IconTabBarEvents: buildImageSource('IconTabBarEvents', 'icon_tabbar_events'),
    IconTabBarEventsSelected: buildImageSource('IconTabBarEventsSelected', 'icon_tabbar_events_selected'),
    IconTabBarProfile: buildImageSource('IconTabBarProfile', 'icon_tabbar_profile'),
    IconTabBarProfileSelected: buildImageSource('IconTabBarProfileSelected', 'icon_tabbar_profile_selected'),
    IconTabBarSettings: buildImageSource('IconTabBarSettings', 'icon_tabbar_settings'),
    IconTabBarSettingsSelected: buildImageSource('IconTabBarSettingsSelected', 'icon_tabbar_settings_selected'),
    IconLock: buildImageSource('IconLock', 'icon_lock'),
    IconChevronLeft: buildImageSource('IconChevronLeft', 'icon_chevron_left'),
    IconChevronRight: buildImageSource('IconChevronRight', 'icon_chevron_right'),
    IconShield: buildImageSource('IconShield', 'icon_shield'),
    IconBell: buildImageSource('IconBell', 'icon_bell'),
    IconAccount: buildImageSource('IconAccount', 'icon_account'),
    IconEvents: buildImageSource('IconEvents', 'icon_events'),
    IconEdit: buildImageSource('IconEdit', 'icon_edit'),
    IconProfile: buildImageSource('IconProfile', 'icon_profile'),
    IconScan: buildImageSource('IconScan', 'icon_scan'),
    IconSettings: buildImageSource('IconSettings', 'icon_settings'),
    IconPlus: buildImageSource('IconPlus', 'icon_plus'),
    IconMinus: buildImageSource('IconMinus', 'icon_minus'),
    IconMoreHorizontal: buildImageSource('IconMoreHorizontal', 'icon_more_horizontal'),
    IconMoreVertical: buildImageSource('IconMoreVertical', 'icon_more_vertical'),
    IconTrash: buildImageSource('IconTrash', 'icon_trash'),
    IconEye: buildImageSource('IconEye', 'icon_eye'),
    IconEyeOff: buildImageSource('IconEyeOff', 'icon_eye_off'),
    IconCamera: buildImageSource('IconCamera', 'icon_camera'),
    IconFilter: buildImageSource('IconFilter', 'icon_filter'),
    IconSearch: buildImageSource('IconSearch', 'icon_search'),
    IconCornerRightUp: buildImageSource('IconCornerRightUp', 'icon_corner_right_up'),
    IconCornerLeftUp: buildImageSource('IconCornerLeftUp', 'icon_corner_left_up'),
    IconCornerRightDown: buildImageSource('IconCornerRightDown', 'icon_corner_right_down'),
    IconX: buildImageSource('IconX', 'icon_x'),
    IconBook: buildImageSource('IconBook', 'icon_book'),
    IconSmartPhone: buildImageSource('IconSmartPhone', 'icon_smartphone'),
    IconSlider: buildImageSource('IconSlider', 'icon_sliders'),
    IconActivity: buildImageSource('IconActivity', 'icon_activity'),
    IconXrp: buildImageSource('IconXrp', 'icon_xrp'),
    IconXrpNew: buildImageSource('IconXrpNew', 'icon_xrp_new'),
    IconShare: buildImageSource('IconShare', 'icon_share'),
    IconCheck: buildImageSource('IconCheck', 'icon_check'),
    IconInfo: buildImageSource('IconInfo', 'icon_info'),
    IconChevronDown: buildImageSource('IconChevronDown', 'icon_chevron_down'),
    IconChevronUp: buildImageSource('IconChevronUp', 'icon_chevron_up'),
    IconClipboard: buildImageSource('IconClipboard', 'icon_clipboard'),
    IconFingerprint: buildImageSource('IconFingerprint', 'icon_fingerprint'),
    IconThumbsUp: buildImageSource('IconThumbsUp', 'icon_thumbs_up'),
    IconLink: buildImageSource('IconLink', 'icon_link'),
    IconHelpCircle: buildImageSource('IconHelpCircle', 'icon_help_circle'),
    IconSend: buildImageSource('IconSend', 'icon_send'),
    IconStar: buildImageSource('IconStar', 'icon_star'),
    IconTrustLine: buildImageSource('IconTrustLine', 'icon_trustline'),
    IconRefresh: buildImageSource('IconRefresh', 'icon_refresh'),
    IconRepeat: buildImageSource('IconRepeat', 'icon_repeat'),
    IconKey: buildImageSource('IconKey', 'icon_key'),
    IconSwitchAccount: buildImageSource('IconSwitchAccount', 'icon_switchaccount'),
    IconGlobe: buildImageSource('IconGlobe', 'icon_globe'),
    IconArrowDown: buildImageSource('IconArrowDown', 'icon_arrow_down'),
    IconFileText: buildImageSource('IconFileText', 'icon_file_text'),
    IconQR: buildImageSource('IconQR', 'icon_qr'),
    IconArrowRightLong: buildImageSource('IconArrowRightLong', 'icon_arrow_right_long'),
    IconCheckXumm: buildImageSource('IconCheckXumm', 'icon_check_xumm'),
    IconApps: buildImageSource('IconApps', 'icon_apps'),
    IconTabbarActions: buildImageSource('IconTabbarActions', 'icon_tabbar_actions'),
    IconReorder: buildImageSource('IconReorder', 'icon_reorder'),
    IconReorderHandle: buildImageSource('IconReorderHandle', 'icon_reorder_handle'),
    IconXApps: buildImageSource('IconXApps', 'icon_xapps'),
    IconXApp: buildImageSource('IconXApp', 'icon_xapp'),
};
