name: prepare-environment
description: Prepare development environment

inputs:
  cocoapods:
      description: 'Setup env with cocoapods'
      required: false
      default: 'false'
  java:
    description: 'Setup env with java'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Cache node_modules/
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - name: Install Node dependencies
      shell: bash
      run: npm ci

    - name: Prepare cocoapods
      if: "${{ inputs.cocoapods == 'true' }}"
      uses: ./.github/actions/prepare-cocoapods

    - name: Prepare source code
      shell: bash
      run: |
        ./scripts/build-env.sh
        mv src/app.tsx src/app.tsx.old && cat src/app.tsx.old|perl -pe'BEGIN{undef $/;} s/if \(isJailBroken.+?}/\/\/ No root or jailbreak detection/gms' > src/app.tsx

