import StyleService from '@services/StyleService';

import { AppSizes, AppFonts } from '@theme';
/* Styles ==================================================================== */
const styles = StyleService.create({
    contentBox: {
        marginBottom: AppSizes.paddingSml,
        paddingHorizontal: 5,
    },
    headerCountContainer: {
        flexDirection: 'row',
    },
    headerTxType: {
        fontSize: AppFonts.small.size,
        fontFamily: AppFonts.small.family,
        fontWeight: 400,
        color: '$white',
        right: 7,
        top: 3,
    },
    headerCount: {
        fontSize: AppFonts.small.size,
        fontFamily: AppFonts.small.family,
        color: '$white',        
        top: 3,
    },
    headerDesc: {
        fontSize: AppFonts.base.size,
        fontFamily: AppFonts.base.family,
        color: '$white',
    },
    headerDescThirdParty: {
        fontSize: AppFonts.p.size,
        fontFamily: AppFonts.base.family,
        color: '$white',
        opacity: 0.6,
    },
    fromAccount: {
        fontSize: AppFonts.subtext.size,
        fontFamily: AppFonts.base.familyBold,
        color: '$grey',
    },
    innerTransactionHeader: {
        backgroundColor: '$blue',
        paddingHorizontal: AppSizes.paddingExtraSml,
        paddingTop: AppSizes.paddingExtraSml / 2,
        paddingBottom: AppSizes.paddingExtraSml / 1.2,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    transactionContainer: {
        backgroundColor: '$blue',
        borderWidth: 3,
        borderColor: '$blue',
        borderRadius: 8,
        marginBottom: AppSizes.paddingSml,
    },
    innerTransactionHeaderThirdParty: {
        backgroundColor: '$grey',
    },
    transactionContainerThirdParty: {
        backgroundColor: '$grey',
        borderColor: '$grey',
        opacity: 1,
    },
    innerTransactionHeaderMineOther: {
        backgroundColor: '$green',
    },
    transactionContainerMineOther: {
        backgroundColor: '$green',
        borderColor: '$green',
        opacity: 1,
    },
    innerTransactionContainerBorder: {
        paddingHorizontal: AppSizes.paddingExtraSml,
        paddingTop: AppSizes.paddingExtraSml,
        borderWidth: 4,
        opacity: 0.95,
        borderColor: '$tint',
        backgroundColor: '$tint',
        borderRadius: 6,
    },
    contentBoxSecondary: {
        paddingTop: AppSizes.paddingExtraSml,
        paddingHorizontal: AppSizes.paddingExtraSml,
        borderRadius: AppSizes.borderRadius,
        backgroundColor: '$tint',
        marginBottom: AppSizes.paddingSml,
    },
    uriTokenContainer: {
        paddingHorizontal: 5,
        paddingVertical: AppSizes.paddingExtraSml,
        backgroundColor: '$light',
    },
    nfTokenContainer: {
        paddingHorizontal: 0,
    },
    memoContainer: {
        marginHorizontal: -8,
        paddingHorizontal: 8,
        paddingTop: 6,
        paddingBottom: 10,
        borderColor: '$lightGrey', 
        borderWidth: 2,
        borderRadius: 6, 
        marginBottom: AppSizes.paddingSml / 3,
    },
    memoType: {
        color: StyleService.select({ light: '$blue', dark: '$textSecondary' }),
    },
    correctMptPadding: {
        marginHorizontal: -20,
    },
    memoFormat: {
        fontWeight: '200',
        color: '$grey',
        fontSize: AppFonts.base.size / 1.3,
    },
    memoData: {
        paddingTop: AppSizes.paddingExtraSml / 2,
        fontWeight: '200',
        color: '$contrast',
    },
    addressContainer: {
        borderRadius: 15,
        zIndex: 2,
        paddingHorizontal: 5,
        paddingVertical: 0,
        marginBottom: AppSizes.paddingSml,
    },
    signersContainer: {
        marginBottom: AppSizes.paddingSml,
    },
    label: {
        fontFamily: AppFonts.subtext.family,
        fontSize: AppFonts.subtext.size,
        fontWeight: 'bold',
        color: '$grey',
        paddingLeft: 5,
        marginBottom: 10,
    },
    labelSmall: {
        fontSize: AppFonts.subtext.size * 0.9,
    },
    destinationAddress: {
        marginTop: 10,
        paddingTop: 10,
        width: '100%',
        borderTopWidth: 1,
        borderTopColor: '$grey',
    },
    amount: {
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        fontSize: AppFonts.h5.size,
        color: '$textPrimary',
    },
    amountRed: {
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        fontSize: AppFonts.h5.size,
        color: '$red',
    },
    value: {
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        fontSize: AppFonts.base.size,
        color: '$textPrimary',
    },
    valueSmall: {
        fontSize: AppFonts.base.size * 0.9,
    },
    valueSubtext: {
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        fontSize: AppFonts.subtext.size,
        color: '$textPrimary',
    },
    address: {
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        fontSize: AppFonts.subtext.size,
        color: '$grey',
    },
    logo: {
        width: AppSizes.screen.width * 0.2,
        height: AppSizes.screen.height * 0.1,
        resizeMode: 'contain',
    },
    avatar: {
        alignSelf: 'center',
        width: AppSizes.scale(90),
        height: AppSizes.scale(90),
        borderRadius: 10,
    },
    editButton: {
        backgroundColor: '$tint',
        borderRadius: 8,
        height: 25,
        width: 40,
        justifyContent: 'center',
        alignSelf: 'center',
        marginRight: 0,
    },
    amountInput: {
        fontSize: AppFonts.h3.size,
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        color: '$blue',
        alignSelf: 'center',
        margin: 0,
        padding: 0,
    },
    alertBox: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'stretch',
        borderRadius: 15,
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '$lightRed',
        borderColor: '$lightRed',
    },
    rateContainer: {
        paddingTop: 15,
    },
    rateText: {
        fontFamily: AppFonts.base.familyMono,
        fontSize: AppFonts.base.size * 0.8,
        color: '$textSecondary',
    },
    feeText: {
        fontFamily: AppFonts.base.familyMonoBold,
        fontWeight: '600',
        fontSize: AppFonts.base.size,
        color: '$textPrimary',
    },
    objectTemplateContainer: {
        marginBottom: AppSizes.paddingSml,
    },
    objectTemplateChildContainer: {
        paddingVertical: 10,
        paddingHorizontal: 5,
    },
    signerEntryDetailsContainer: {
        paddingVertical: 10,
        paddingHorizontal: 8,
        marginBottom: 10,
        backgroundColor: '$tint',
        borderWidth: 2,
        borderColor: '$tint',
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        borderTopColor: '$lightGrey',
    },
    authorizeCredentialsContainer: {
        paddingVertical: 10,
        paddingHorizontal: 8,
        backgroundColor: '$tint',
        borderWidth: 2,
        borderColor: '$tint',
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        borderTopColor: '$lightGrey',
    },
    credentialContainer: {
        borderStyle: 'solid',
        borderWidth: 1,
        borderRadius: 12,
        borderColor: '$tint',
        marginBottom: 10,
    },
    attachedAccountElement: {
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
    },
    hookParamText: {
        backgroundColor: '$tint',
        borderRadius: 10,
        overflow: 'hidden',
    },
    copyText: {
        fontFamily: AppFonts.base.familyBold,
        fontSize: AppFonts.subtext.size,
        color: '$grey',
        paddingRight: 5,
    },
    copyButton: {
        flexDirection: 'row',
        paddingHorizontal: AppSizes.paddingExtraSml,
    },
    jsonTreeContainer: {
        backgroundColor: StyleService.select({ light: '$light', dark: '$tint' }),
        borderRadius: AppSizes.borderRadius,
        padding: AppSizes.paddingExtraSml,
        marginBottom: AppSizes.paddingSml,
    },
});

export default styles;
