name: Android CI

on:
  push:
    branches: [ github-actions-test ]

jobs:
  test:
    runs-on: macos-latest-large
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build tests
        run: |
          pushd android
          ./gradlew app:assembleAndroidTest
          popd

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          ndk: 25.1.8937393
          cmake: 3.18.1
          script: cd android; ./gradlew app:connectedAndroidTest
