name: ios
env:
  CI: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build-test:
    if: github.event.pull_request.draft == false
    runs-on: [ self-hosted, macOS, ARM64 ]
    strategy:
      matrix:
        ios: [ 18.3.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Environment
        uses: ./.github/actions/prepare-env
        with:
          cocoapods: 'true'

      - name: Run tests
        working-directory: ios
        run: |
          xcodebuild -quiet -workspace Xaman.xcworkspace -scheme Xaman -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=${{ matrix.ios }}' -resultBundlePath TestResults.xcresult test
          echo "Exit code: $?"
      
      - name: Check for xcresult
        working-directory: ios
        run: |
          ls -la
          if [ -d "TestResults.xcresult" ]; then echo "Found TestResults.xcresult"; else echo "TestResults.xcresult not found"; fi
          
      - name: Test Summary
        uses: slidoapp/xcresulttool@v3.1.0
        with:
          path: ios/TestResults.xcresult
        if: success() || failure()
